### ISSUE TITLE
tutorial fails with example html files, out of bounds error

### ISSUE THREAD

**Issue by JPBergsma** [olivettigroup/table_extractor#1] opened 2019-12-18 11:45 UTC
Dear Jensen 

A colleague wants to make a database of zeolites and their synthesis conditions. I therefore tried to run this table extractor to extract data about zeolite synthesis conditions. 

When I however try to run the table extracter tutorial with jupyter-notebook on the file 101021acscgd8b00078.html I get the error shown below.

To get the script running I installed scikit-learn version 0.19.1 instead of sklearn.
If I installed sklearn I got a warning about a version mismatch and I could not find the correct version of sklearn.

I further more had to replace 'en' on line 27 with 'en_core_web_sm' as it did not recognize 'en'

Perhaps this is also because of a different package version.

Do you still remember which package versions you used, and perhaps how to solve this issue?
Thank you.

`Extracting Tables (HTML) from:  10.1021/acs.cgd.8b00078
3 3 3

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-166fc1858716> in <module>()
      1 # Supported domain names = zeolites, geopolymers, steel, titanium, aluminum, alloys
      2 te = TableExtractor(domain_name='zeolites')
----> 3 tables = te.extract_and_save_all_tables(files, dois)

/home/johan/ownCloud/Documents/postdoc Amsterdam/zeoliteextroctor for ilse/table_extractor-master/tableextractor/table_extractor.py in extract_and_save_all_tables(self, files, dois)
     52                 print(len(tables), len(captions), len(footers))
     53                 cols, rows, col_inds, row_inds = self.get_headers(tables)
---> 54                 pred_cols, pred_rows = self.classify_table_headers(cols, rows)
     55                 orients = []
     56                 composition_flags = []

/home/johan/ownCloud/Documents/postdoc Amsterdam/zeoliteextroctor for ilse/table_extractor-master/tableextractor/table_extractor.py in classify_table_headers(self, cols, rows)
    828         vect_rows = []
    829         for col, row in zip(cols, rows):
--> 830             vect_c, label = self.vectorize_words(col, [0]*len(col))
    831             vect_r, label = self.vectorize_words(row, [0]*len(row))
    832             vect_cols.append(self.clf.predict(vect_c))

/home/johan/ownCloud/Documents/postdoc Amsterdam/zeoliteextroctor for ilse/table_extractor-master/tableextractor/table_extractor.py in vectorize_words(self, words, labels)
    817         for word, label in zip(words, labels):
    818             if str(word) in self.embeddings:
--> 819                 emb_vector.append(self.embeddings[str(word)])
    820                 label_vector.append(label)
    821             else:

/home/johan/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py in __getitem__(self, entities)
    351         if isinstance(entities, string_types):
    352             # allow calls like trained_model['office'], as a shorthand for trained_model[['office']]
--> 353             return self.get_vector(entities)
    354 
    355         return vstack([self.get_vector(entity) for entity in entities])

/home/johan/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py in get_vector(self, word)
    469 
    470     def get_vector(self, word):
--> 471         return self.word_vec(word)
    472 
    473     def words_closer_than(self, w1, w2):

/home/johan/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py in word_vec(self, word, use_norm)
   2132                 return word_vec
   2133             for nh in ngram_hashes:
-> 2134                 word_vec += ngram_weights[nh]
   2135             return word_vec / len(ngram_hashes)
   2136 

IndexError: index 1998876 is out of bounds for axis 0 with size 1990189

`

When I tried to run the script for the other html file 101016jmicromeso201806043.html
I got the following result 

Extracting Tables (HTML) from:  10.1016/j.micromeso.2018.06.043
0 0 0
Finished Extracting all Papers
Number Attempted: 1
Number Successful: 0
Number Failed: 0

**Comment by zjensen262** [comment] 2019-12-19 18:48
Here are a few of the versions used for this:
python - 3.6.7
sklearn- 0.19.1
spacy- 2.0.11
gensim- 3.4.0
Let me know if that solves your issues. I'm not sure what is causing the error, but my first guess is a version issue with one of the above packages. Also make sure you have all four files from here, https://figshare.com/s/70455cfcd0084a504745, in the /bin folder

**Comment by JPBergsma** [comment] 2020-01-28 12:40
Sorry for my late response somehow I missed your post.
The program still does not work. After downgrading spacy to 2.0.11 i get another error:
ImportError: cannot import name 'msgpack'
This probably happens because I do not have the correct version of the thinc package on which spacy depends.This newer version of thinc probably got installed because one of the other packages also depends on it.
Could you perhaps execute pip freeze to generate the whole list of packages?

**Comment by zjensen262** [comment] 2020-01-31 18:07
Here is the pip freeze read-out. Many of these probably are not requirements
absl-py==0.2.2
amqp==2.3.2
anyjson==0.3.3
appdirs==1.4.3
apturl==0.5.2
articledownloader==9.1
astor==0.6.2
atomicwrites==1.1.5
attrs==18.1.0
Autologging==1.1.0
backcall==0.1.0
beautifulsoup4==4.4.1
bibtexparser==1.0.1
billiard==3.5.0.3
bleach==1.5.0
blinker==1.3
boto==2.48.0
boto3==1.7.30
botocore==1.10.30
Brlapi==0.6.4
bz2file==0.98
celery==4.2.1
chardet==2.3.0
checkbox-support==0.22
ChemDataExtractor==1.3.0
click==6.7
cloudpickle==0.5.3
command-not-found==0.3
coverage==4.5.1
cryptography==1.2.3
cssselect==1.0.3
cycler==0.10.0
cymem==1.31.2
cytoolz==0.8.2
dask==0.17.5
DAWG==0.7.8
decorator==4.3.0
defer==1.0.6
dill==0.2.7.1
distributed==1.21.8
docutils==0.14
en-core-web-sm==2.0.0
entrypoints==0.2.3
feedparser==5.1.3
Flask==1.0.2
future==0.16.0
fuzzywuzzy==0.17.0
gast==0.2.0
gensim==3.4.0
grpcio==1.12.0
guacamole==0.9.2
h5py==2.7.1
HeapDict==1.0.0
html5lib==0.9999999
httplib2==0.9.1
hyperas==0.4
hyperopt==0.1
idna==2.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
itsdangerous==0.24
jedi==0.12.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
Keras==2.1.6
keras-bert==0.80.0
keras-embed-sim==0.7.0
keras-layer-normalization==0.13.0
keras-multi-head==0.22.0
keras-pos-embd==0.11.0
keras-position-wise-feed-forward==0.6.0
keras-self-attention==0.41.0
keras-transformer==0.31.0
kiwisolver==1.0.1
kombu==4.2.1
language-selector==0.1
locket==0.2.0
louis==2.6.4
lxml==4.2.1
Mako==1.0.3
Markdown==2.6.11
MarkupSafe==0.23
matplotlib==2.2.2
mistune==0.8.3
monty==1.0.2
more-itertools==4.2.0
mpmath==1.0.0
msgpack==0.5.6
msgpack-numpy==0.4.1
msgpack-python==0.5.6
murmurhash==0.28.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numpy==1.14.3
oauthlib==1.0.3
onboard==1.2.0
padme==1.1.1
palettable==3.1.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.1
partd==0.3.8
pathlib==1.0.1
pdfminer.six==20170720
pexpect==4.0.1
pickleshare==0.7.4
Pillow==3.1.2
plac==0.9.6
plainbox==0.25
pluggy==0.6.0
preshed==1.0.0
prompt-toolkit==1.0.15
protobuf==3.5.2.post1
psutil==5.4.6
ptyprocess==0.5
PubChemPy==1.0.4
py==1.5.3
pyasn1==0.1.9
pycryptodome==3.6.1
pycups==1.9.73
pycurl==7.43.0
PyDispatcher==2.0.5
Pygments==2.2.0
pygobject==3.20.0
PyJWT==1.3.0
pymatgen==2018.5.22
pymongo==3.6.1
pyparsing==2.0.3
pytest==3.6.0
python-apt==1.1.0b1+ubuntu0.16.4.8
python-crfsuite==0.9.5
python-dateutil==2.7.3
python-debian==0.1.27
python-Levenshtein==0.12.0
python-systemd==231
pytz==2018.4
pyxdg==0.25
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
redis==2.10.6
regex==2017.4.5
reportlab==3.3.0
requests==2.9.1
ruamel.yaml==0.15.37
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.1.0
seaborn==0.8.1
Send2Trash==1.5.0
sessioninstaller==0.0.0
simplegeneric==0.8.1
six==1.10.0
smart-open==1.5.7
sortedcontainers==2.0.4
spacy==2.0.11
spglib==1.10.3.65
ssh-import-id==5.5
sympy==1.1.1
system-service==0.3
tabulate==0.8.2
tblib==1.3.2
tensorboard==1.8.0
tensorflow==1.8.0
tensorflow-hub==0.1.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
thinc==6.10.2
toolz==0.9.0
tornado==5.0.2
tqdm==4.23.4
traitlets==4.3.2
ubuntu-drivers-common==0.0.0
ufw==0.35
ujson==1.35
unattended-upgrades==0.1
Unidecode==1.0.22
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.13.1
usb-creator==0.3.0
vine==1.1.4
wcwidth==0.1.7
Werkzeug==0.14.1
widgetsnbextension==3.2.1
wrapt==1.10.11
xdiagnose==3.8.4.1
xkit==0.0.0
xlrd==1.2.0
XlsxWriter==0.7.3
zict==0.1.3

**Comment by JPBergsma** [comment] 2020-02-25 15:39
Thank you for posting the list. I still tried twice to setup an environment like yours.
Unfortunatly some of the package combinations you have seem to be incompattible. And I run into bugs in some older versions of these packages that have been fixed in newer versions. Therefore I will stop trying to run this program.

**Comment by AndreudeDonato** [comment] 2020-04-27 16:34
I have found the same out of bounds error as Kwlbus.
I do not know how to code, so forgive my ignorance, is the aritlce-downloader necessary to run the table_extractor?

Thanks in advance

**Comment by zjensen262** [comment] 2020-05-12 13:19
Sorry for taking so long to fix this. The out-of-bounds error seems to have been coming from issues with backward compatibility with word embedding models trained on gensim 3.4 and then being used on 3.7 and up. I developed a work-around for this issue that should fix the bug. I also fixed the spacy compatibility issue so the version of spacy should no longer matter. One final change is replacing one of the example html files. I discovered it was only the abstract page rather than the full paper page.  I've confirmed these changes on gensim 3.8.1, but I believe they should work on all versions >= 3.4. Just pull to the most up-to-date version of this repository. Article-downloader is not necessary to run this package. I will leave this issue open in case there are additional issues

**Comment by zakidotai** [comment] 2021-01-21 02:56
Hi @zjensen262 ,
Thanks for making this code open source. I was able to run the examples after forking and cloning the repo and downloading required modules.
However, when I tried to run other doi (10.1016/j.jnoncrysol.2012.05.024), two columns of table 1 are not getting extracted namely 'Glass' and 'Index'. Can you please see if this is a bug which requires fixing?

**Comment by zjensen262** [comment] 2021-01-22 15:50
It is very difficult to debug for a single paper since it is hard to generalize across all tables since the HTML/XML structure can change depending on when/where you get the paper from. Are you seeing this same issue across many different papers? This could indicate a broader issue I'd be happy to look at.

**Comment by zakidotai** [comment] 2021-01-22 16:00
Thanks @zjensen262 .
I also tried another paper (10.1016/j.jnoncrysol.2012.01.030) and the Table 1 here is much complex then the previous one, yet, your pipeline was able to extract all the columns and I was able to convert the data into a dataframe. Also, both the papers are from the same journal of Elsevier, and you have used tables from the same journal(paper-1 : 10.1016/j.jnoncrysol.2012.05.024) in your dissolution rate paper (it forms the validation set).

I guess we should look at the XML of both the tables to figure this out. Thanks in advance.

FYI : I used "geopolymer" as domain name.

**Comment by zakidotai** [comment] 2021-03-01 07:36
> It is very difficult to debug for a single paper since it is hard to generalize across all tables since the HTML/XML structure can change depending on when/where you get the paper from. Are you seeing this same issue across many different papers? This could indicate a broader issue I'd be happy to look at.

Hi @zjensen262 , I was able to resolve the difficulties. You can close this issue.

**Closed as completed** 2021-03-01 12:04 UTC
